# Generated by Django 2.1.5 on 2019-02-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_password_set', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('is_owner', 'is owner'), ('is_enterprise_admin', 'is enterprise admin'), ('is_enterprise_editor', 'is enterprise editor'), ('is_enterprise_viewer', 'is enterprise viewer'), ('is_default_admin', 'is default admin'), ('is_default_editor', 'is default editor'), ('is_default_viewer', 'is default viewer'), ('is_guest', 'is guest')),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32)),
                ('role', models.CharField(default='Owner', max_length=32)),
                ('available', models.BooleanField(default=True)),
                ('thumbnail', models.FileField(blank=True, default='images/user.svg', upload_to='users/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
