version: "3"
   
services:
  goserver:
    container_name: goserver
    build:
      context: ./goserver
    ports:
      - "${GO_SERVER_PORT}:${GO_SERVER_PORT}"
    volumes:
      - "./goserver:/goserver"
    networks:
      - go_network
networks:
  go_network:
    driver: bridge