version: "3"
   
services:
  goserver:
    container_name: goserver
    build:
      context: ./goserver
    ports:
      - "${COLLIDER_SERVER_PORT}:${COLLIDER_SERVER_PORT}"
    expose:
      - "${COLLIDER_SERVER_PORT}"

    restart: on-failure

    volumes:
      - "./goserver:/goserver"
    networks:
      - go_network
networks:
  go_network:
    driver: bridge