# Generated by Django 4.1.3 on 2022-12-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_interval',
            field=models.CharField(default='30', max_length=2),
        ),
    ]
