# Generated by Django 4.1.5 on 2023-01-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Etc/GMT+0', max_length=64),
        ),
    ]
