version: "3"
   
services:
  videochat_client:
    container_name: videochat_client
    build:
      context: ./videochat/client
    command: npm run watch
    environment: 
      - NODE_ENV=development
    networks:
      videochat_network:
        ipv4_address: 192.170.0.11

    volumes:
      - "./videochat/client:/client/"

networks:
  videochat_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.170.0.0/24