version: "3"

networks:
  videochat_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.170.0.0/24
   
services:

  videochat_pyserver:
    container_name: videochat_pyserver
    build:
      context: ./videochat/pyserver
      args:
        DJANGO_ALLOWED_HOSTS: '*'
        DJANGO_SECRET_KEY: '*'
    command: bash -c "python manage.py migrate && gunicorn --certfile=${CERT_FILE} --keyfile=${KEY_FILE} --reload qhv2.wsgi --bind 0.0.0.0:${APP_PORT}"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - "./videochat/pyserver:/pyserver"
    networks:
       videochat_network:
          ipv4_address: 192.170.0.10

    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TURN_SERVER_BASE_URL=${TURN_SERVER_BASE_URL}
      - TURN_SERVER_USERNAME=${TURN_SERVER_USERNAME}
      - COLLIDER_SERVER_PORT=${COLLIDER_SERVER_PORT}      
      - COLLIDER_SERVER_BASE_URL=${COLLIDER_SERVER_BASE_URL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}

      - CERT_FILE=${CERT_FILE}
      - KEY_FILE=${KEY_FILE}

      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - SECRET_KEY=${SECRET_KEY}

    depends_on:
      - goserver
      - redis

  videochat_client:
    container_name: videochat_client
    build:
      context: ./videochat/client
    command: npm run watch
    environment: 
      - NODE_ENV=development
    networks:
      videochat_network:
        ipv4_address: 192.170.0.11

    volumes:
      - "./videochat/client:/client/"

  redis:
    container_name: redis
    build:
      context: ./videochat/redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"
    volumes:
      - "./videochat/redis:/redis"
    networks:
      videochat_network:
        ipv4_address: 192.170.0.12

