version: "3"
   
services:
  videochat_client:
    container_name: videochat_client
    build:
      context: ./videochat/client
    command: npm run watch
    environment: 
      - NODE_ENV=development
    volumes:
      - "./videochat/client:/client/"