# Generated by Django 3.2.4 on 2021-10-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210930_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationsession',
            name='rate',
            field=models.SmallIntegerField(default=0),
        ),
    ]
