# Generated by Django 4.1.3 on 2022-11-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_communication_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationSettings',
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
