# Generated by Django 4.1.3 on 2022-12-15 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_userworkinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
