# Generated by Django 4.1.3 on 2022-12-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_communication_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='short_url',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
