# Generated by Django 4.1.3 on 2022-12-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_communication_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'pending'), (2, 'open'), (3, 'rejected'), (5, 'cancelled'), (4, 'closed')], default=1),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'video call'), (2, 'message')], default=2),
        ),
    ]
