# Generated by Django 4.1.3 on 2022-12-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_communication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='one_day_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communication',
            name='one_hour_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communication',
            name='reminders',
            field=models.BooleanField(default=True),
        ),
    ]
