# Generated by Django 4.1.5 on 2023-01-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_communication_one_day_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='calendar_attachment',
            field=models.FileField(blank=True, upload_to='calendars/'),
        ),
    ]
