version: "3"
   
services:
  console_client:
    build:
      context: ./console/client
    command: npm run watch
    environment: 
      - NODE_ENV=development
    volumes:
      - "./console/client:/client/"