version: "3"

services:

  console_client:
    build:
      context: ./console/client
    command: npm run watch
    environment: 
      - NODE_ENV=development
    volumes:
      - "./console/client:/client/"
      - "./console/pyserver/console/static/images:/static/images"
    networks:
      console_network:
         ipv4_address: 192.180.0.22

networks:
  console_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.180.0.0/24