# Generated by Django 2.1.5 on 2019-02-04 19:02

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(default='', max_length=256)),
                ('value', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ClientBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(default='anonymous_guest', max_length=256)),
                ('modification_time', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'created'), (2, 'pending'), (3, 'closed'), (4, 'completed')], default=1)),
                ('caller', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client_board', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ClientBoard')),
            ],
            options={
                'get_latest_by': ['modification_time'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('close_time', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'video call'), (2, 'message')], default=1)),
                ('status', models.SmallIntegerField(choices=[(1, 'created'), (2, 'posted'), (3, 'missed'), (4, 'cancelled'), (5, 'rejected'), (6, 'accepted'), (7, 'completed')], default=1)),
                ('attendant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('communication', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Communication')),
            ],
            options={
                'verbose_name': 'communication_session',
                'verbose_name_plural': 'communication_sessions',
                'db_table': 'dashboard_communication_session',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Domain', max_length=256)),
                ('url', models.CharField(max_length=512, validators=[dashboard.models.full_domain_validator])),
                ('lang', models.CharField(default='en', max_length=5)),
                ('last_change', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('is_installed', models.BooleanField(default=False)),
                ('paused', models.BooleanField(default=False)),
                ('header', models.CharField(blank=True, max_length=256)),
                ('content', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('assignees', models.ManyToManyField(related_name='widget_user', to=settings.AUTH_USER_MODEL)),
                ('client_board', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ClientBoard')),
                ('last_editor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.TextField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('background_color', models.CharField(default='7FD100', max_length=6)),
                ('icon', models.FileField(blank=True, default='images/logo.svg', upload_to='widget_templates/images')),
                ('type', models.CharField(choices=[('ST', 'Standalone'), ('IN', 'Inline')], default='ST', max_length=2)),
                ('last_editor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='widget',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.WidgetTemplate'),
        ),
        migrations.AddField(
            model_name='communication',
            name='widget',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='dashboard.Widget'),
        ),
    ]
