# Generated by Django 3.1.5 on 2021-06-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190204_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgettemplate',
            name='type',
        ),
    ]
