# Generated by Django 3.2.4 on 2021-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_communicationsession_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'open'), (2, 'pending'), (3, 'closed'), (4, 'completed')], default=1),
        ),
    ]
